/**
 * Chat History Types -- Data models for persisting chat sessions in IndexedDB.
 */

import type { ChatMessage } from '@sogni-ai/sogni-client';
import type { Suggestion } from '@/utils/chatSuggestions';
import type { ToolExecutionProgress, UploadedFile } from '@/tools/types';

/** UI message (extends ChatMessage with display metadata) */
export interface UIChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
  imageResults?: string[];
  videoResults?: string[];
  audioResults?: string[];
  toolProgress?: ToolExecutionProgress | null;
  isStreaming?: boolean;
  /** Streaming status text (e.g. "Thinking...") — transient, cleared after streaming */
  streamingStatus?: string;
  /** Chat model variant label (e.g. "Sogni Agent · Auto") — transient */
  chatModelLabel?: string;
  lastCompletedTool?: string;
  uploadedImageUrl?: string;
  /** Multiple uploaded image preview URLs (for multi-image sessions) */
  uploadedImageUrls?: string[];
  sourceImageUrl?: string;
  modelRefusal?: boolean;
  galleryImageIds?: string[];
  galleryVideoIds?: string[];
  galleryAudioIds?: string[];
  videoAspectRatio?: string;
  /** Display name of the AI model used for this result (e.g. "Z-Image Turbo") */
  modelName?: string;
  /** Original tool arguments used for this result (for retry/switch model) */
  toolArgs?: Record<string, unknown>;
  /** Model key used for this result (e.g. "z-turbo", "qwen-lightning") */
  toolModelKey?: string;
  /** Transient flag: true for messages restored from session history (not persisted) */
  isFromHistory?: boolean;
  /** True for messages created by the offline recovery system */
  isRecoveryMessage?: boolean;
}

/** Full chat session stored in IndexedDB */
export interface ChatSession {
  /** Unique session ID (UUID) */
  id: string;
  /** Session title (first user message or filename) */
  title: string;
  /** Timestamp when session was created */
  createdAt: number;
  /** Timestamp when session was last modified */
  updatedAt: number;
  /** Whether this session is pinned to the top of the sidebar */
  pinned?: boolean;
  /** UI messages for rendering */
  uiMessages: UIChatMessage[];
  /** LLM conversation history (raw ChatMessages for API) */
  conversation: ChatMessage[];
  /** All result image URLs produced in this session */
  allResultUrls: string[];
  /** Audio result URLs generated by tools (e.g. generate_music) — used by sound_to_video */
  audioResultUrls?: string[];
  /** Suggestions parsed from vision analysis */
  analysisSuggestions: Suggestion[];
  /** If the session was switched to abliterated model, persist that choice */
  sessionModel?: string;
  /** Attached files (images, audio, video) persisted for session restoration */
  uploadedFiles?: UploadedFile[];
  // Legacy fields — kept for backward compat with sessions saved before unified uploads
  /** @deprecated Use uploadedFiles instead */
  imageData?: Uint8Array;
  /** @deprecated Use uploadedFiles instead */
  width?: number;
  /** @deprecated Use uploadedFiles instead */
  height?: number;
}

/** Lightweight session summary for sidebar list (no heavy data) */
export interface ChatSessionSummary {
  id: string;
  title: string;
  createdAt: number;
  updatedAt: number;
  /** Whether this session has an uploaded image */
  hasImage: boolean;
  /** Whether this session is pinned to the top of the sidebar */
  pinned?: boolean;
}

/** Thumbnail blob stored separately for efficient sidebar rendering */
export interface ChatSessionThumbnail {
  /** Session ID this thumbnail belongs to */
  sessionId: string;
  /** Thumbnail image blob (small JPEG) */
  blob: Blob;
}
