/**
 * Tool definition for sound_to_video.
 * Based on workflow_sound_to_video.mjs — audio-driven video generation.
 */

import type { ToolDefinition } from '@sogni-ai/sogni-client';
import { ASPECT_RATIO_DESCRIPTION } from '../shared';

export const definition: ToolDefinition = {
  type: 'function',
  function: {
    name: 'sound_to_video',
    description:
      'Generate video synchronized to audio. Works with EITHER: (1) a user-uploaded audio file (mp3, wav, m4a), OR (2) audio previously generated by generate_music in this session. Use this tool when the user wants video synced to audio — such as music videos, lip-sync, music visualization, or audio-reactive motion. If generate_music was used earlier in the conversation, this tool can automatically use that generated audio (no upload needed). If the user wants dialogue, speaking, or audio in their video WITHOUT any pre-existing audio, use animate_photo instead (LTX 2.3 generates audio natively).',
    parameters: {
      type: 'object',
      properties: {
        prompt: {
          type: 'string',
          description: `Visual description of the video to generate, synchronized to the audio. 2-4 sentences.

For lip-sync (with a face image):
- Describe the person's appearance and how they speak: "A person speaking naturally with synchronized lip movements, warm expression, soft studio lighting."
- Include atmosphere: "In a cozy living room with warm bokeh lights in the background."

For music visualization (no face needed):
- Describe the visual style that reacts to the music: "Abstract colorful waveforms pulsing to the beat, neon lights flowing across a dark background."
- Match the mood to the music: "Energetic geometric shapes exploding outward in sync with drum beats."

For audio-reactive (general):
- Describe visual elements that should move with the audio: "Ocean waves rising and falling in rhythm with the ambient sounds."

CONSTRAINTS:
- Present tense. Positive phrasing. Concrete details.
- Describe motion as it relates to the audio.`,
        },
        audioSourceIndex: {
          type: 'number',
          description:
            'Index of the uploaded audio file to use (0-based, from uploaded files list). If only one audio file is uploaded, use 0. If no audio was uploaded but generate_music was used earlier, omit this — the tool will automatically find the generated audio.',
        },
        sourceImageIndex: {
          type: 'number',
          description:
            'Optional index of an uploaded image to use as the starting frame (0-based). Required for lip-sync models (WAN S2V). For audio-only-to-video models (LTX 2.3 A2V), this is optional — omit it to generate video purely from text + audio.',
        },
        duration: {
          type: 'number',
          description:
            'Video duration in seconds. Default: matches audio length (up to 10s). Range: 2-10.',
          minimum: 2,
          maximum: 10,
        },
        videoModel: {
          type: 'string',
          enum: ['wan-s2v', 'ltx23-ia2v', 'ltx23-a2v'],
          description:
            'Video model. "wan-s2v" (default): WAN 2.2 sound-to-video, best for lip-sync with a face image, fast 4-step. "ltx23-ia2v": LTX 2.3 image+audio to video, audio-reactive with a reference image, 8-step. "ltx23-a2v": LTX 2.3 audio-only to video, no image needed, creates video purely from text prompt + audio. Default: "wan-s2v".',
        },
        numberOfVariations: {
          type: 'number',
          description:
            'Number of video variations to generate (1-16). Default: 1.',
          minimum: 1,
          maximum: 16,
        },
        aspectRatio: {
          type: 'string',
          description: ASPECT_RATIO_DESCRIPTION,
        },
      },
      required: ['prompt'],
    },
  },
};
