/**
 * Core type definitions for the tool registry system.
 *
 * Each tool is a self-contained module that implements the ToolHandler interface.
 * The registry manages discovery, definition export (for the LLM), and dispatch.
 */

import type { ToolDefinition } from '@sogni-ai/sogni-client';
import type { SogniClient } from '@sogni-ai/sogni-client';
import type { TokenType, Balances } from '@/types/wallet';

// ---------------------------------------------------------------------------
// Uploaded files
// ---------------------------------------------------------------------------

/** File uploaded by user (image, audio, or video) */
export interface UploadedFile {
  type: 'image' | 'audio' | 'video';
  data: Uint8Array;
  width?: number;
  height?: number;
  mimeType: string;
  filename: string;
  /** Duration in seconds (for audio/video) */
  duration?: number;
}

// ---------------------------------------------------------------------------
// Tool execution context
// ---------------------------------------------------------------------------

/** Context available to every tool handler during execution */
export interface ToolExecutionContext {
  sogniClient: SogniClient;
  /** Primary image data (from upload) */
  imageData: Uint8Array | null;
  width: number;
  height: number;
  /** Additional uploaded files (audio, video, extra images) */
  uploadedFiles: UploadedFile[];
  tokenType: TokenType;
  /** URLs of previously generated results in this session */
  resultUrls: string[];
  /** URLs of audio results generated by tools (e.g. generate_music) in this session */
  audioResultUrls: string[];
  /** URLs of video results generated by tools in this session */
  videoResultUrls: string[];
  /** Current wallet balances for auto-switch logic */
  balances: Balances | null;
  /** Default quality tier set by the UI toggle */
  qualityTier?: 'fast' | 'hq' | 'pro';
  /** Called when token type is auto-switched due to insufficient balance */
  onTokenSwitch?: (newType: TokenType) => void;
  /** Called when both token types are exhausted */
  onInsufficientCredits?: () => void;
  /** AbortSignal for cancelling in-progress tool executions */
  signal?: AbortSignal;
  /** Override the LLM model (e.g. for abliterated fallback) */
  model?: string;
  /** Override the think parameter (true = extended thinking, false = disabled, undefined = default) */
  think?: boolean;
  /** Whether the safe content filter is enabled (true = filter on, false = filter off). Default: true. */
  safeContentFilter?: boolean;
  /** Called when the content filter setting is changed (e.g. by the set_content_filter tool) */
  onContentFilterChange?: (enabled: boolean) => void;
  /** Request to disable the content filter — shows confirmation popup, resolves true if confirmed */
  requestDisableContentFilter?: () => Promise<boolean>;
  /** Current chat session ID — used by projectSessionMap for offline recovery */
  sessionId: string;
}

// ---------------------------------------------------------------------------
// Tool names
// ---------------------------------------------------------------------------

/** Tool name union */
export type ToolName =
  | 'restore_photo'
  | 'apply_style'
  | 'refine_result'
  | 'animate_photo'
  | 'change_angle'
  | 'generate_image'
  | 'edit_image'
  | 'generate_video'
  | 'sound_to_video'
  | 'video_to_video'
  | 'generate_music'
  | 'analyze_image'
  | 'set_content_filter'
  | 'extract_metadata'
  | 'resolve_personas'
  | 'manage_memory'
  | 'stitch_video'
  | 'orbit_video'
  | 'dance_montage';

// ---------------------------------------------------------------------------
// Progress & callbacks
// ---------------------------------------------------------------------------

/** Progress callback from tool execution */
export interface ToolExecutionProgress {
  type: 'started' | 'progress' | 'completed' | 'error';
  toolName: ToolName;
  progress?: number;
  completedCount?: number;
  totalCount?: number;
  resultUrls?: string[];
  /** Video result URLs (separate from image results for UI rendering) */
  videoResultUrls?: string[];
  error?: string;
  jobIndex?: number;
  etaSeconds?: number;
  /** Estimated credit cost for this operation */
  estimatedCost?: number;
  /** URL of the source image being processed (for placeholder display) */
  sourceImageUrl?: string;
  /** URLs of additional context images used (for multi-image placeholder display, e.g. persona + source) */
  contextImageUrls?: string[];
  /** URL of the end-frame image when frameRole is "both" (for dual-frame video placeholder) */
  endFrameImageUrl?: string;
  /** Sub-step label shown during multi-phase operations (e.g. "Analyzing image...") */
  stepLabel?: string;
  /** Per-job label for concurrent operations (stored into perJobProgress[i].label) */
  jobLabel?: string;
  /** Target video aspect ratio as "w / h" CSS string (e.g. "9 / 16") for preloader sizing */
  videoAspectRatio?: string;
  /** Display name of the AI model used (e.g. "Z-Image Turbo", "LTX-2") */
  modelName?: string;
  /** Persona names referenced during this tool execution (for UI indicator) */
  referencedPersonas?: string[];
  /** When set, show a confirm/proceed button. UI calls triggerRetry(confirmKey) on click. */
  confirmKey?: string;
  /** Label for the confirm button (e.g. "Stitch Montage"). Defaults to "Confirm". */
  confirmLabel?: string;
  /** Descriptive text shown alongside the confirm button (e.g. "Redo clips you want to change.") */
  confirmDescription?: string;
  /** Accumulated per-job progress for multi-job operations (keyed by jobIndex) */
  perJobProgress?: Record<number, {
    progress?: number;
    etaSeconds?: number;
    resultUrl?: string;
    error?: string;
    /** True when resultUrl is a video (vs image). Used by pipeline steps that mix media types. */
    isVideo?: boolean;
    /** Per-job display label (e.g. "Generating right side view") */
    label?: string;
    /** When set, the UI should show a retry button that calls triggerRetry(retryKey) */
    retryKey?: string;
  }>;
}

/** Callbacks for tool execution — subset of ChatStreamCallbacks */
export interface ToolCallbacks {
  onToolProgress: (progress: ToolExecutionProgress) => void;
  onToolComplete: (toolName: ToolName, resultUrls: string[], videoResultUrls?: string[]) => void;
  onInsufficientCredits?: () => void;
  onGallerySaved?: (galleryImageIds: string[], galleryVideoIds: string[], galleryAudioIds?: string[]) => void;
}

// ---------------------------------------------------------------------------
// Suggestion chips
// ---------------------------------------------------------------------------

/** Suggestion chip shown after tool completion */
export interface ToolSuggestion {
  label: string;
  prompt: string;
}

// ---------------------------------------------------------------------------
// Tool handler interface
// ---------------------------------------------------------------------------

/** A tool handler that can be registered with the ToolRegistry */
export interface ToolHandler {
  /** OpenAI-format tool definition (passed to the LLM) */
  definition: ToolDefinition;
  /** Execute the tool and return a JSON string result for the LLM */
  execute(
    args: Record<string, unknown>,
    context: ToolExecutionContext,
    callbacks: ToolCallbacks,
  ): Promise<string>;
  /** Optional suggestion chips to show after this tool completes */
  suggestions?: ToolSuggestion[];
  /** Side-effect level for policy enforcement */
  sideEffectLevel?: 'read' | 'write' | 'destructive';
  /** Per-tool timeout override in ms (default: 300_000) */
  timeoutMs?: number;
  /** Retry policy for transient failures */
  retryPolicy?: {
    maxAttempts: number;
    backoffMs: number;
    retryOn: ('transient' | 'timeout' | 'credits')[];
  };
  /** Whether this tool can safely run in parallel with other tools */
  canRunInParallel?: boolean;
}

// ---------------------------------------------------------------------------
// Error categories
// ---------------------------------------------------------------------------

/** Typed error categories for structured error handling */
export type ToolErrorCategory =
  | 'schema_validation'    // Malformed or missing arguments
  | 'business_rule'        // Valid args but violates business logic
  | 'precondition_failed'  // Dependency or prerequisite not met
  | 'transient_failure'    // Temporary failure, safe to retry
  | 'permanent_failure'    // Unrecoverable tool error
  | 'insufficient_credits' // Balance too low
  | 'timeout'              // Tool execution timed out
  | 'cancelled'            // User or system aborted
  | 'content_refused';     // Model refused due to content policy

// ---------------------------------------------------------------------------
// Result envelope
// ---------------------------------------------------------------------------

/** Structured result envelope wrapping every tool execution outcome */
export interface ToolResultEnvelope {
  success: boolean;
  toolName: ToolName;
  /** Validated arguments that were passed to the executor */
  args: Record<string, unknown>;
  /** Duration of execution in milliseconds */
  durationMs: number;

  // --- Success fields ---
  /** Raw JSON string result from the tool handler */
  rawResult?: string;
  /** Image URLs produced */
  resultUrls?: string[];
  /** Video URLs produced */
  videoResultUrls?: string[];
  /** Audio URLs produced */
  audioResultUrls?: string[];

  // --- Error fields ---
  error?: string;
  errorCategory?: ToolErrorCategory;
  /** Whether this error is safe to retry */
  retryable?: boolean;
  /** Number of retry attempts made */
  retryCount?: number;

  // --- Metadata ---
  /** Estimated credit cost */
  estimatedCost?: number;
  /** Model used for generation */
  model?: string;
  /** Trace ID for correlation */
  traceId?: string;
}
